---
name: GO CI
on:
  push:
    branches: [main]
  workflow_dispatch:
defaults:
  run:
    working-directory: sample-kanban-go
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - run: go build -v ./...
      - run: go test -cover -v ./...
