---
name: JVM CI
on:
  push:
    branches: [main]
  workflow_dispatch:
defaults:
  run:
    working-directory: sample-kanban-jvm
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
         distribution: oracle
         java-version: 17
      - run: ./gradlew build bootJar
